exoscale/pithos

- src/io/pithos/sig.clj
- test/io/pithos/sig_test.clj
When both headers are present, the `Date` header should be ignored and
the corresponding line in the signature should be empty. Also add some unittests.
> Fix signature when both `Date` and `x-amz-date` headers are present

- src/io/pithos/operations.clj
At least the JClouds S3 Client requires this header. I do not see why it should harm to always add it.
> respond with Last-Modified header on get-object

- src/io/pithos/util.clj
The main difference is to use time offsets instead of the
symbolic name UTC.
According to the original RFC822 UTC would not be allowed.
According to the proposed successor RFC2822 offsets are to be
preferred to use.
RFC 822 http://www.w3.org/Protocols/rfc822/#z28
RFC 2822 http://www.rfc-editor.org/rfc/rfc2822.txt
see clj-time.format rfc822 pattern "EEE, dd MMM yyyy HH:mm:ss Z"
https://github.com/clj-time/clj-time/blob/v0.8.0/src/clj_time/format.clj#L138
> Use clj-time.format rfc822 formatter

- tasks/leiningen/fatdeb.clj
- tasks/leiningen/fatrpm.clj
- tasks/leiningen/tar.clj
Added in missing descriptions, and spelling fix.
> Fixing up lein fatrpm, fatdeb and tar task descriptions for consistency.

- doc/source/clients.rst
Updating s3cmd docs to make this clear. I was stuck on this for a bit today before seeing an issue that said the v4 signatures were on the horizon.
> Use v2 signature with s3cmd

- project.clj
Just adding this one back - looks like it got overwritten in an auto-merge.
> Putting back lein-rpm dependency

- src/io/pithos/config.clj
- src/io/pithos/operations.clj
- src/io/pithos/system.clj
If a client interface needs automatic access to a deployed pithos installation, this will prove useful.
The configuration now accepts an addition `default-cors` option:
```yaml
options:
default-cors:
- origins: [ "*"]
- methods: [ "post" ]
- headers: [ "Content-Type" ]
- exposed: [ ]
```
> cors: allow server provided default-cors rules

- src/io/pithos/cors.clj
- src/io/pithos/xml.clj
when dealing about CORS error messages report ACL errors. This aims to fix this, reporting CORS errors when dealing with CORS.
> report CORS error instead of ACL error when dealing with CORS

- doc/s3cmd.cfg
2144dbefee8e822aefb4785dfb39ac60f611765e updated the documentation, but left out the sample s3cmd configuration file in `doc/`.
> Update s3cmd example configuration to use v2 signature.

- src/io/pithos/cors.clj
S3 docs mention `ExposeHeader`, not `ExposedHeader`.
> Fix ExposeHeader

- src/io/pithos/util.clj
RFC822 allows for trailing timezones, but some S3 clients expect
GMT to be present. This commit, forces the output TZ of RFC822
timestamps to be GMT to unbreak these parsers.
> util: force RFC822 to be GMT, fixes #78

- src/io/pithos/request.clj
https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html
says:
"Separate parameter names from their values with the equal sign
character (=) (ASCII character 61), even if the value is empty."
This doesn't seem to be true for signature generation though and
existing S3 client libraries (goamz, minio-go) encounter an
authentication error when talking to Pithos, since Pithos is including
'=' for a query string '?a='.
https://github.com/aws/aws-sdk-go/blob/1a69d069352edadd48f12b0f2c5f375de4a636d7/private/signer/v2/v2.go#L133-L139
seems to confirm Pithos behavior, *but* the v2 signer in aws-sdk-go is
SimpleDB specific (see https://github.com/aws/aws-sdk-go/issues/400) and
appears to not be officially supported.
So our best guess is to follow the implementations in-use.
> sig: fix signing for query string w/ empty vals

- src/io/pithos/operations.clj
Last-Modified header is only returned on HEAD object.
I haven't tested this.
> operations: get-object return last-modified header

- src/io/pithos/operations.clj
- test/io/pithos/operations_test.clj
This restricts what a bucket name be composed of to the
following heuristic:
- A string of 3 to 63 characters.
- Alphanumeric characters.
- Dots, hyphens and underscores allowed.
> operations: stricter rules for bucket naming.

- src/io/pithos/operations.clj
Without this, 206 ressponses emitted by pithos are not RFC7233 compliant.
> operations: add content-range header in response

- src/io/pithos/blob.clj
- src/io/pithos/bucket.clj
- src/io/pithos/meta.clj
- src/io/pithos/store.clj
Instead of hardcoding the consistency level for pithos queries,
leave it to installations to specify it.
We let each store create functions to execute at write or read
consistency level. The default is quorum for all queries.
> store: per request consistency options

- src/io/pithos/meta.clj
When we have no value for the delimiter query arg, treat it as nil. This will fix #80
> Treat empty delimiters as nils

- src/io/pithos/blob.clj
This is a follow-up to https://github.com/exoscale/pithos/commit/548795e2bb1217efb8edeb2dc9588041da820872.
Instead of second-guessing what a sensible maximum would be for
chunks sizes, do a lazy fetch. Lazyness is alright here since
we always consume the resulting seq with doseq or last.
> blob: fetch chunks in slices to relieve memory pressure.

- src/io/pithos/operations.clj
- src/io/pithos/request.clj
- src/io/pithos/util.clj
When copying from an existing key, ensure that we correctly decode the source bucket and key.
> operations: encode source when copying object

- src/io/pithos/operations.clj
- src/io/pithos/perms.clj
When bucket owner != tenant, give them both FULL_CONTROL permissions instead
of only the bucket owner. Additionally request only has `:od` in
`put-object`. This avoids getting 'nil' grantees in ACLs.
> Fix #121 -- give uploader FULL_CONTROL permissions

- src/io/pithos/schema.clj
After running into the inconvenience of detecting a failed 'install-schema' action due to 'successful' exit codes, I attempted to make  the exit codes more accurate.
I will admit that I am a clojure novice, so apologies if this is non-idiomatic.
> Use exit code 1 if install schema fails, or 0 otherwise

- src/io/pithos/operations.clj
- src/io/pithos/xml.clj
Since pithos does not support request payment options, this is
a noop for now and fixes visual inconveniences.
> operations: add get-bucket-requestpayment handler

- src/io/pithos/meta.clj
- test/io/pithos/meta_test.clj
- test/io/pithos/operations_test.clj
In object lists, when the given prefix is itself a key, it
is excluded from search results. This introduces a behavioral change
from AWS S3's approach and breaks s3cmd for cases such as:
```
s3cmd ls s3://bucket/object.txt
```
Provided here is a slight modification to the fetcher callback
signature, accounting for an `init?` argument where queries
may include the prefix itself in searches.
> meta: include object itself in prefix search. fixes #117

- src/io/pithos/desc.clj
This avoids returning 403 errors when non-bucket owners with enough
permissions (like FULL_CONTROL on bucket) try reading non-existing objects.
> descriptor: fallback to bucket ACLs for inexisting objects

- src/io/pithos/stream.clj
Do not iterate over chunks that are outside the expected range.
> stream: guard crop-chunk access

- src/io/pithos/sig.clj
This allows authenticated users to access objects with public-read-like permissions.
> sig: consider authenticated users members of anonymous users as well

- src/io/pithos/desc.clj
- src/io/pithos/xml.clj
Real-world usage reports show that some conditions may lead to partial metadata being written on objects.
This captures the condition, fails requests and provides context to better get at the root-cause of such issues.
> desc: warn on attempts to write incomplete metadata

- project.clj
- src/io/pithos/store.clj
Options specified in https://mpenet.github.io/alia/qbits.alia.html#var-cluster will now be directly threaded to the client library.
> allow threading of cassandra cluster options through alia

- .travis.yml
- project.clj
The original com.eaio.uuid package maintainer seems to not have pushed
version 3.3 of uuid to a reliable public repository. This fixes the
problem by forcing the use of 3.2 instead.
Tests pass and it doesn't seem like 3.2 regresses anything.
This fixes #165 
I also took the opportunity to fix the travis file (they switched from lein1 to lein2 as default).
> Prevent eaio uuid from being fetched over HTTP

- doc/pithos.yaml
- src/io/pithos/request.clj
- src/io/pithos/sig4.clj
- test/io/pithos/sig4_test.clj
As of e75d433 I am able to create buckets, list bucket contents, upload and then download files using s3cmd. I've done multipart uploads of > 20 parts happily with it. I have also had it working with other internal s3 stuff, including ranged requests.
This is still very WIP - and only targets a subset of the sig4 signing styles (e.g. no chunked uploads).
It's definitely not ready to merge, but i have no prior experience with clojure and I don't know quite how bad this is 😱, so early feedback would be good.
There are also some questions for the maintainers.
* `:uri` is replaced. Bucket path rewriting happens before the authorization code runs. This was invalidating the signatures. So i create an `:orig-uri` before this happens. Is there a better way?
* You can only read `:body` once. For …
> WIP: Signature 4 support

- doc/source/clients.rst
Included non-standard port configuration requirements
Using BasicAWSCredentials (instead of credentials file) to use keys obtained by Java client through other means (db, config files, etc.)
> Update clients.rs - updated AWS Java SDK section
